### ISSUE TITLE
Parser: consider ANTLR with Swift target

### ISSUE THREAD

**Issue by johnpannell** [brentsimmons/Frontier#1]
Hey Brent - 

Your Frontier articles keep popping up on my feed - twice now you've referred to parsing and both times I've wanted to tell you "Hey - you should check out ANTLR and their new swift target for code generation."  I've been using it in a project, and it is pretty slick.  OK - finicky to set up, but then slick.  I'm submitting this as an issue since I couldn't find another way to message you :-) Let me know if I can provide any details...

**Comment by brentsimmons** [comment]
I didn’t know about ANTLR — could be just the thing! Thanks, John.

**Comment by johnpannell** [comment]
If you head down this road (learning new parser-generator tech probably isn't the Indiana Jones solution :-) ...

https://pragprog.com/book/tpantlr2/the-definitive-antlr-4-reference

Book does a great job of explaining how to get ANTLR to do the hard work for you, and how you can use the generated code to interact with the parse tree (listener/visitor).  While it mentions language targets, it doesn't go into any detail.  Everything is Java, ANTLR's native language.

Generating the same tokenizer/parser in the desired language is a command line option, assuming the target is present in ANTLR.  Swift recently became available, Obj-C is not.

$ antlr4 -Dlanguage=Swift MyGrammar.g4 

Getting the generated code and the ANTLR runtime into your app is outlined here:

https://github.com/antlr/antlr4/blob/master/doc/swift-target.md

Once the code and runtime are in place, Xcode auto-complete is a godsend for figuring out context while listening for the tree being walked.  Feels very swift-y and native.

**Comment by johnpannell** [comment]
ANTLR is on homebrew, if you're a fan of it.

**Comment by deverman** [comment]
@brentsimmons great to hear about your attempts to resurrect Frontier. I was a heavy user in the late 90's. heard you announce it on a couple podcasts. Sorry this comment has nothing to do with the issue. Couldn't find anyway to contact you to give some encouragement.

**Comment by brentsimmons** [comment]
I’ve decided to write it all by hand. I’ve done a bunch of the work already.

Main reason: this is something I’ve always wanted to do. The chance is unlikely to come again.
